core_frontend:
    resource: "@BannerCoreBundle/Controller/Frontend/CoreController.php"
    type: annotation
city_frontend:
    resource: "@BannerCoreBundle/Controller/Frontend/CityController.php"
    type: annotation
content_frontend:
    resource: "@BannerCoreBundle/Controller/Frontend/ContentController.php"
    type: annotation
mailing_frontend:
    resource: "@BannerCoreBundle/Controller/Frontend/MailingController.php"
    type: annotation
    prefix:   /mailing
mailing_backend:
    resource: "@BannerCoreBundle/Controller/Backend/MailingController.php"
    type: annotation
    prefix:   admin/mailing
banner_backend:
    resource: "@BannerCoreBundle/Controller/Backend/BannerController.php"
    type: annotation
    prefix:   admin/banner
city_backend:
    resource: "@BannerCoreBundle/Controller/Backend/CityController.php"
    type: annotation
    prefix:   /admin/cidade
category_backend:
    resource: "@BannerCoreBundle/Controller/Backend/CategoryController.php"
    type: annotation
    prefix:   /admin/categoria
content_backend:
    resource: "@BannerCoreBundle/Controller/Backend/ContentController.php"
    type: annotation
    prefix:   /admin/paginas
html_frontend:
    resource: "@BannerCoreBundle/Controller/Frontend/HtmlController.php"
    type: annotation