status_backend:
    resource: "@BannerOrderBundle/Controller/Backend/StatusController.php"
    type: annotation
    prefix:   /admin/status
size_backend:
    resource: "@BannerOrderBundle/Controller/Backend/SizeController.php"
    type: annotation
    prefix:   /admin/tamanho
discount_backend:
    resource: "@BannerOrderBundle/Controller/Backend/DiscountController.php"
    type: annotation
    prefix:   /admin/desconto
discount_frontend:
    resource: "@BannerOrderBundle/Controller/Frontend/DiscountController.php"
    type: annotation
    prefix:   /desconto
order_frontend:
    resource: "@BannerOrderBundle/Controller/Frontend/OrderController.php"
    type: annotation
order_frontend:
    resource: "@BannerOrderBundle/Controller/Frontend/OrderController.php"
    type: annotation
    prefix:   /pedido
    
