TuvaisCoreBundle:
    resource: "@TuvaisCoreBundle/Resources/config/routing/routing.yml"
TuvaisUserBundle:
   resource:  "@TuvaisUserBundle/Resources/config/routing/routing.yml"
MastopSystemBundle:
  resource: "@MastopSystemBundle/Resources/config/routing/routing.yml"
MastopMenuBundle:
  resource: "@MastopMenuBundle/Resources/config/routing/routing.yml"
MastopTesteBundle:
    resource: "@MastopTesteBundle/Resources/config/routing/teste.yml"
   
_login:
    resource: "@TuvaisUserBundle/Controller/Frontend/SecurityController.php"
    type:     annotation
    requirements:
        _scheme:  https
_logout:
    resource: "@TuvaisUserBundle/Controller/Frontend/SecurityController.php"
    type:     annotation
login_check:
    pattern:   /login_check

_home:
    pattern:  /
    defaults: { _controller: TuvaisCoreBundle:Frontend\Core:index }
    requirements:
      _scheme: http
